const fs = require('node:fs')
const path = require('node:path')
const asciidoctor = require('asciidoctor')()
const NumberedCaptions = require('../src')

const source = `= asciidoctor-numbered-captions demo
:sectnums:
:stem: latexmath

== Chapter A

.Sample figure in chapter A
image::https://dummyimage.com/420x120/f3f4f6/111827.png&text=Figure+A[Demo image,420,120]

.Sample table in chapter A
|===
|Key |Value

|alpha |1
|beta |2
|===

.Sample equation in chapter A
[stem]
++++
a^2 + b^2 = c^2
++++

== Chapter B

.Sample figure in chapter B
image::https://dummyimage.com/420x120/e0f2fe/111827.png&text=Figure+B[Demo image,420,120]

.Sample table in chapter B
|===
|Key |Value

|gamma |3
|delta |4
|===

.Sample equation in chapter B
[stem]
++++
\\int_0^1 x^2 dx = 1/3
++++
`

const defaultHtml = asciidoctor.convert(source, {
  safe: 'safe',
  backend: 'html5'
})

const registry = asciidoctor.Extensions.create()
NumberedCaptions.register(registry, {
  chapterLevel: 1,
  labels: {
    image: 'Figure',
    table: 'Table',
    stem: 'Equation'
  }
})

const pluginHtml = asciidoctor.convert(source, {
  safe: 'safe',
  backend: 'html5',
  extension_registry: registry
})

const outDir = path.join(process.cwd(), 'docs')
const outPath = path.join(outDir, 'index.html')
fs.mkdirSync(outDir, { recursive: true })

const page = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>asciidoctor-numbered-captions demo</title>
    <style>
      :root {
        color-scheme: light;
      }

      body {
        font-family: system-ui, sans-serif;
        margin: 2rem auto;
        max-width: 1400px;
        line-height: 1.6;
        padding: 0 1rem;
        color: #111827;
      }

      .meta {
        color: #4b5563;
        font-size: 0.95rem;
      }

      .preview-grid {
        display: grid;
        grid-template-columns: repeat(2, minmax(0, 1fr));
        gap: 1rem;
        align-items: start;
      }

      .preview-panel {
        border: 1px solid #d1d5db;
        border-radius: 8px;
        background: #ffffff;
        min-width: 0;
      }

      .preview-panel h2 {
        margin: 0;
        padding: 0.75rem 1rem;
        font-size: 1rem;
        border-bottom: 1px solid #e5e7eb;
        background: #f9fafb;
      }

      .preview-body {
        padding: 1rem;
        overflow-x: auto;
      }

      .preview-body img {
        border: 1px solid #d1d5db;
        border-radius: 6px;
      }

      .preview-body table {
        border-collapse: collapse;
      }

      .preview-body th,
      .preview-body td {
        border: 1px solid #d1d5db;
        padding: 0.4rem 0.6rem;
      }

      .preview-body .imageblock > .title,
      .preview-body .tableblock > .title,
      .preview-body .stemblock > .title {
        background: #fff7cc;
        border-radius: 4px;
        padding: 0.1rem 0.35rem;
        display: inline-block;
      }

      @media (max-width: 960px) {
        .preview-grid {
          grid-template-columns: 1fr;
        }
      }
    </style>
  </head>
  <body>
    <h1>asciidoctor-numbered-captions demo</h1>
    <p class="meta">Generated by <code>npm run build:demo</code>. Left is default Asciidoctor output, right applies <code>NumberedCaptions.register(...)</code>.</p>
    <div class="preview-grid">
      <section class="preview-panel">
        <h2>Default Asciidoctor output</h2>
        <div class="preview-body">${defaultHtml}</div>
      </section>
      <section class="preview-panel">
        <h2>With asciidoctor-numbered-captions</h2>
        <div class="preview-body">${pluginHtml}</div>
      </section>
    </div>
  </body>
</html>
`

fs.writeFileSync(outPath, page)
console.log(`Demo site generated: ${outPath}`)
