const fs = require('node:fs')
const path = require('node:path')
const asciidoctor = require('asciidoctor')()
const numberedCaptions = require('../src')

const registry = asciidoctor.Extensions.create()
numberedCaptions.register(registry, {
  chapterLevel: 1,
  labels: {
    image: 'Figure',
    table: 'Table',
    stem: 'Equation'
  }
})

const source = `= asciidoctor-numbered-captions demo
:sectnums:
:stem: latexmath

== Chapter A

.Sample figure in chapter A
image::https://dummyimage.com/420x120/f3f4f6/111827.png&text=Figure+A[Demo image,420,120]

.Sample table in chapter A
|===
|Key |Value

|alpha |1
|beta |2
|===

[stem]
++++
a^2 + b^2 = c^2
++++

== Chapter B

.Sample figure in chapter B
image::https://dummyimage.com/420x120/e0f2fe/111827.png&text=Figure+B[Demo image,420,120]
`

const htmlBody = asciidoctor.convert(source, {
  safe: 'safe',
  backend: 'html5',
  extension_registry: registry
})

const outDir = path.join(process.cwd(), 'docs')
const outPath = path.join(outDir, 'index.html')
fs.mkdirSync(outDir, { recursive: true })

const page = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>asciidoctor-numbered-captions demo</title>
    <style>
      body { font-family: system-ui, sans-serif; margin: 2rem auto; max-width: 960px; line-height: 1.6; padding: 0 1rem; }
      .meta { color: #4b5563; font-size: 0.95rem; }
      img { border: 1px solid #d1d5db; border-radius: 6px; }
      table { border-collapse: collapse; }
      th, td { border: 1px solid #d1d5db; padding: 0.4rem 0.6rem; }
    </style>
  </head>
  <body>
    <h1>asciidoctor-numbered-captions demo</h1>
    <p class="meta">Generated by <code>npm run build:demo</code>.</p>
    ${htmlBody}
  </body>
</html>
`

fs.writeFileSync(outPath, page)
console.log(`Demo site generated: ${outPath}`)
